### ISSUE TITLE
Regression.pdf notation

### ISSUE THREAD

**Issue by erenatas** [tevfikaytekin/data_science#1]
Under Ridge Regression's Gradient Descent part, is this part correct?

![image](https://user-images.githubusercontent.com/4595094/49074850-a2565700-f246-11e8-831a-d58ef28f735e.png)

Shouldn't it be 
![image](https://user-images.githubusercontent.com/4595094/49074968-e6e1f280-f246-11e8-9a66-9e9bcfdfeedc.png)

if this part is the cost function?

By the way, thank you for uploading them to Github.

**Comment by tevfikaytekin** [comment]
Yes, you are right
